---
- name: Install HashiCorp repository and Terraform
  hosts: ec2_instances
  become: true
  tasks:
    - name: Add HashiCorp GPG key
      apt_key:
        url: https://apt.releases.hashicorp.com/gpg
        state: present

    - name: Install Terraform
      apt:
        name: terraform
        state: present
