---
- name: Install Ansible
  hosts: ec2_instances
  become: true
  tasks:
    - name: Add Ansible PPA
      apt_repository:
        repo: 'ppa:ansible/ansible'
        state: present

    - name: Update package list
      apt:
        update_cache: yes

    - name: Install Ansible
      apt:
        name: ansible
        state: present
