---
- name: Install Terraform
  hosts: ec2_instances
  become: true
  tasks:
    - name: Install required packages
      apt:
        name:
          - wget
          - curl
          - unzip
          - software-properties-common
          - gpg
        state: present

    - name: Add HashiCorp GPG key
      apt_key:
        url: https://apt.releases.hashicorp.com/gpg
        state: present

    - name: Add HashiCorp repository
      apt_repository:
        repo: "deb [arch=$(dpkg --print-architecture)] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
        state: present

    - name: Update package list
      apt:
        update_cache: yes

    - name: Install Terraform
      apt:
        name: terraform
        state: present

    - name: Display Terraform version
      command: terraform -v
